apiVersion: v1
kind: Service
metadata:
  name: {{ include "tftp-server.fullname" . }}
  labels:
    {{- include "tftp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tftp
      port: {{ .Values.service.port }}
      targetPort: tftp
      protocol: UDP
  selector:
    {{- include "tftp-server.selectorLabels" . | nindent 4 }}
